version: '3.7'

services:
  # n8n service
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n_user
      - DB_POSTGRESDB_PASSWORD=n8n_password
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_PUBLIC_API=true
      - N8N_LOG_LEVEL=info
      - TZ=America/Sao_Paulo
    ports:
      - "5678:5678"
    depends_on:
      - db
    volumes:
      - n8n_data:/root/.n8n
    restart: unless-stopped
    networks:
      - bridge

  # PostgreSQL service
  db:
    image: postgres:13
    container_name: n8n_db
    environment:
      - POSTGRES_USER=n8n_user
      - POSTGRES_PASSWORD=n8n_password
      - POSTGRES_DB=n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - bridge

  # Evolution API service
  evolution:
    image: atendai/evolution-api:latest
    container_name: evolution
    volumes:
      - evolution_instances:/evolution/instances
    environment:
      # Configurações Gerais
      - SERVER_URL=http://localhost:8080
      - AUTHENTICATION_API_KEY=429683C4C977415CAAFCCE10F7D57E11
      - AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES=true
      - DEL_INSTANCE=false
      - QRCODE_LIMIT=1902
      - LANGUAGE=pt-BR
      
      # Configuração do Cliente
      - CONFIG_SESSION_PHONE_VERSION=2.3000.1021437297
      - CONFIG_SESSION_PHONE_CLIENT=Admin
      - CONFIG_SESSION_PHONE_NAME=Chrome
      
      # Configuração do Banco de Dados (conexão com o PostgreSQL)
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://n8n_user:n8n_password@db:5432/evolution
      - DATABASE_CONNECTION_CLIENT_NAME=evolution
      - DATABASE_SAVE_DATA_INSTANCE=true
      - DATABASE_SAVE_DATA_NEW_MESSAGE=true
      - DATABASE_SAVE_MESSAGE_UPDATE=true
      - DATABASE_SAVE_DATA_CONTACTS=true
      - DATABASE_SAVE_DATA_CHATS=true
      - DATABASE_SAVE_DATA_LABELS=true
      - DATABASE_SAVE_DATA_HISTORIC=true
      
      # Integração com OpenAI, Dify, Typebot e Chatwoot
      - OPENAI_ENABLED=true
      - DIFY_ENABLED=true
      - TYPEBOT_ENABLED=true
      - TYPEBOT_API_VERSION=latest
      - CHATWOOT_ENABLED=true
      - CHATWOOT_MESSAGE_READ=true
      - CHATWOOT_MESSAGE_DELETE=true
      - CHATWOOT_IMPORT_DATABASE_CONNECTION_URI=postgresql://n8n_user:n8n_password@db:5432/chatwoot?sslmode=disable
      - CHATWOOT_IMPORT_PLACEHOLDER_MEDIA_MESSAGE=false
      
      # Configuração do Cache Redis
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://redis:6379/8
      - CACHE_REDIS_PREFIX_KEY=evolution
      - CACHE_REDIS_SAVE_INSTANCES=false
      - CACHE_LOCAL_ENABLED=false
      
      # Configuração do S3 (desabilitado por padrão)
      - S3_ENABLED=false
      - S3_ACCESS_KEY=
      - S3_SECRET_KEY=
      - S3_BUCKET=evolution
      - S3_PORT=443
      - S3_ENDPOINT=
      - S3_USE_SSL=true

      # Configuração do WhatsApp Business
      - WA_BUSINESS_TOKEN_WEBHOOK=evolution
      - WA_BUSINESS_URL=https://graph.facebook.com
      - WA_BUSINESS_VERSION=v20.0
      - WA_BUSINESS_LANGUAGE=pt_BR

      # Outras configurações como Telemetria, WebSocket, SQS, RabbitMQ, Webhook
      - TELEMETRY=false
      - WEBSOCKET_ENABLED=false
      - WEBHOOK_GLOBAL_ENABLED=false
      - RABBITMQ_ENABLED=false

    restart: unless-stopped
    networks:
      - bridge
    ports:
      - "8080:8080"  # Expondo a API da Evolution na porta 8080

  # Redis service (cache para o Evolution API)
  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - bridge
    restart: unless-stopped

volumes:
  n8n_data:
  postgres_data:
  evolution_instances:

networks:
  bridge:
    driver: bridge
